### PR TITLE
add speech-to-text example

### PR DESCRIPTION
**Pull request by TbhT**
with `baidu-aip-sdk` ， translate voice to text

### CODE REVIEW

**Comment by zixia** [comment]
Thanks for the PR.

However, as we had already an example to do this at <https://github.com/Chatie/wechaty-getting-started/blob/master/examples/professional/speech-to-text-bot.ts>, what's the reason that you create a new one? 

And please note that your PR had included many unrelated changes, and they had already outdated too.

**Comment by TbhT** [comment]
Coding the example is to run project more quickly. Developers should focus on the project's `api`s. More,  this examples is coded with `typescript`. In contrast to `TypeScript`,  `JavaScript` may be better to know the project's `api`s.

**Comment by zixia** [comment]
Okay, I'll not disagree if you want to replace the TypeScript example with JavaScript as you believe the vanilla JavaScript is better.

But this PR is not clean because it also includes many commits which is not related to the example.

Could you please fix them first, so we can focus on the code about the example?

**Comment by TbhT** [comment]
Haha,  it's all right to me with `typescript` or `javascript`.  And i will amend commits.  Or close this PR?

**Comment by zixia** [comment]
I believe what we need to do is to sync your clone with the upstream first.

**Pull request closed without merging**
