### PR TITLE
modify: add padplus to third-party

### PR DESCRIPTION
**Pull request by su-chang**
## I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

_please describe the changes that you are making_

_for features, please describe how to use the new feature_

_please include a reference to an existing issue, if applicable_

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by su-chang** [comment]
Related issue: https://github.com/wechaty/wechaty-getting-started/issues/91

**Comment by su-chang** [comment]
@lijiarui Please review this PR, thank you.

**Comment by su-chang** [comment]
@lijiarui ping

**Comment by huan** [comment]
Close this PR because we should treat all puppets just as an environment variable in our getting started example.

Other 3rd party puppet examples will be removed as well in the future.

**Pull request closed without merging**
