### PR TITLE
fix: Update .travis.yml

### PR DESCRIPTION
**Pull request by suntong**
- fix `npm ls` error causing travis build to fail

## I'm submitting a...

```
[X] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [X] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [X] Tests for the changes have been added

## Description

- fix `npm ls` error causing travis build to fail

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

### CODE REVIEW

**Comment by suntong** [comment]
[#209.1 passed](https://travis-ci.com/github/wechaty/wechaty-getting-started/jobs/318592087)

> The command "npm ls grpc wechaty ..." exited with 0.

others are still being processed.

**Comment by suntong** [comment]
Mac passed as well. Windows failed due to another issue

`The command "npm test" exited with 1.`

**Comment by huan** [comment]
Please feel free to push new commits to this PR so that we can get to know how about our repo doing under different OSs and Node versions.

**Comment by suntong** [comment]
hmm... I'm done, sorry bro, as the _`npm ls` error causing travis build to fail_ has been fixed :)  

I.e., I really don't know Node & Windows much to fix the windows' problem sir, :(

**Comment by suntong** [comment]
Now I'm truly done. Please merge, to have CI tested in master.

**Comment by suntong** [comment]
? -- OK?

Need to clear this one to fix https://github.com/wechaty/wechaty-getting-started/issues/106

thx

**Comment by huan** [comment]
Ok

**Comment by suntong** [comment]
thanks sir.

**Pull request merged**
